service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    GOOGLE_GEOCODE_API_KEY: ${env:GOOGLE_GEOCODE_API_KEY}

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

functions:
  getLocation:
    handler: location/handler.get
    events:
      - http:
          path: location
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin