service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs12.x

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

functions:
  getLocation:
    handler: location/handler.get
    events:
      - http:
          path: location
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline